spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    open-in-view: false